### ISSUE TITLE
Can't find in add-ins after installation

### ISSUE THREAD

**Issue by joeflack4** [skranz/ReplaceInFiles#1]
Hey there! Thanks for writing this awesome add-in.

I can't seem to find it after installation, though. If you check the following screenshots, you'll see in my console that I've installed the add-in. But when I browse for add-ins, I don't see it. None of these add-ins were there before as well, until I ran,

```r
if (!require(devtools)) install.packages("devtools")
devtools::install_github("skranz/ReplaceInFiles")
```

Now I see add-ins, but not yours.

# 1
<img width="1280" alt="Screen Shot 2019-12-23 at 3 40 11 PM" src="https://user-images.githubusercontent.com/13045020/71379804-c051d080-259a-11ea-90b7-a68bde1ff3ed.png">

# 2
<img width="1280" alt="Screen Shot 2019-12-23 at 3 40 18 PM" src="https://user-images.githubusercontent.com/13045020/71379805-c051d080-259a-11ea-889a-47e171dbd103.png">

**Comment by skranz** [comment]
Sorry, for the late reply. Unfortunately, I have no idea why it does not work on your computer. I just followed the RStudio Guidelines on how to write addins, and on my computer it does work. Have you restarted RStudio? Here are answers to similar questions:

https://community.rstudio.com/t/addins-not-showing-after-re-installing-r-and-r-packages/33412

https://github.com/daattali/addinslist/issues/40

**Comment by joeflack4** [comment]
It works now! I guess I just needed to restart RStudio.
